baseURL = "http://example.org/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Projeto"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "mine"





